const container = require('./plugins/container.js')

const ctaColors = {
  primary: 'var(--cta-prim-default)',
  'primary-hover': 'var(--cta-prim-hover)',
  'primary-press': 'var(--cta-prim-press)',
  negative: 'var(--cta-negative)',
  disabled: 'var(--cta-disabled)',
  inverted: 'var(--cta-inverted)',
}

module.exports = {
  content: [],
  theme: {
    screens: {
      xs: '320px',
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1441px',
      '3xl': '1921px',
    },
    fontFamily: {
      sans: 'Roboto',
      serif: 'Roboto',
      mono: 'Roboto',
      display: 'Roboto',
      body: 'Roboto',
    },
    fontSize: {
      // Primitives
      // Heading
      'heading-4xl': ['8rem', { lineHeight: '1' }], // 128px,
      'heading-3xl': ['6rem', { lineHeight: '1' }], // 96px,,
      'heading-2xl': ['4.5rem', { lineHeight: '1' }], // 72px,
      'heading-xl': ['3.75rem', { lineHeight: '1' }], // 60px,
      'heading-lg': ['3rem', { lineHeight: '1' }], // 48px,
      'heading-md': ['2.25rem', { lineHeight: '2.5rem' }], // 36px,
      'heading-sm': ['1.875rem', { lineHeight: '2.25rem' }], // 30px,
      'heading-xs': ['1.5rem', { lineHeight: '2rem' }], // 24px,
      // Body
      'body-xl': ['1.25rem', { lineHeight: '1.75rem' }], // 20px,
      'body-lg': ['1.125rem', { lineHeight: '1.75rem' }], // 18px,
      'body-base': ['1rem', { lineHeight: '1.5rem' }], // 16px,
      'body-sm': ['0.875rem', { lineHeight: '1.25rem' }], // 14px,
      // Label
      'label-lg': ['1rem', { lineHeight: '1rem' }], // 16px,
      'label-sm': ['0.875rem', { lineHeight: '0.875rem' }], // 14px,
      'label-xs': ['0.75rem', { lineHeight: '0.75rem' }], // 12px,
      // Caption
      caption: ['0.75rem', { lineHeight: '1rem' }], //12px
    },
    extend: {
      colors: {
        // Primitive colors
        cta: ctaColors,
        opacity: {
          black: 'var(--opacity-black)',
          white: 'var(--opacity-white)',
          primary: 'var(--opacity-primary)',
          transparent: 'var(--opacity-transparent)',
        },
        carbon: {
          white: 'var(--carbon-white)',
          0: 'var(--carbon-0)',
          25: 'var(--carbon-25)',
          50: 'var(--carbon-50)',
          75: 'var(--carbon-75)',
          100: 'var(--carbon-100)',
          200: 'var(--carbon-200)',
          300: 'var(--carbon-300)',
          400: 'var(--carbon-400)',
          500: 'var(--carbon-500)',
          600: 'var(--carbon-600)',
          700: 'var(--carbon-700)',
          800: 'var(--carbon-800)',
          900: 'var(--carbon-900)',
        },
        blue: {
          50: 'var(--blue-50)',
          75: 'var(--blue-75)',
          100: 'var(--blue-100)',
          200: 'var(--blue-200)',
          300: 'var(--blue-300)',
          400: 'var(--blue-400)',
          500: 'var(--blue-500)',
          600: 'var(--blue-600)',
          700: 'var(--blue-700)',
          800: 'var(--blue-800)',
          900: 'var(--blue-900)',
        },
        orange: {
          50: 'var(--orange-50)',
          75: 'var(--orange-75)',
          100: 'var(--orange-100)',
          200: 'var(--orange-200)',
          300: 'var(--orange-300)',
          400: 'var(--orange-400)',
          500: 'var(--orange-500)',
          600: 'var(--orange-600)',
          700: 'var(--orange-700)',
          800: 'var(--orange-800)',
          900: 'var(--orange-900)',
        },
        info: {
          50: 'var(--info-50)',
          75: 'var(--info-75)',
          100: 'var(--info-100)',
          200: 'var(--info-200)',
          300: 'var(--info-300)',
          400: 'var(--info-400)',
          500: 'var(--info-500)',
          600: 'var(--info-600)',
          700: 'var(--info-700)',
          800: 'var(--info-800)',
          900: 'var(--info-900)',
        },
        error: {
          50: 'var(--error-50)',
          75: 'var(--error-75)',
          100: 'var(--error-100)',
          200: 'var(--error-200)',
          300: 'var(--error-300)',
          400: 'var(--error-400)',
          500: 'var(--error-500)',
          600: 'var(--error-600)',
          700: 'var(--error-700)',
          800: 'var(--error-800)',
          900: 'var(--error-900)',
        },
        warning: {
          50: 'var(--warning-50)',
          75: 'var(--warning-75)',
          100: 'var(--warning-100)',
          200: 'var(--warning-200)',
          300: 'var(--warning-300)',
          400: 'var(--warning-400)',
          500: 'var(--warning-500)',
          600: 'var(--warning-600)',
          700: 'var(--warning-700)',
          800: 'var(--warning-800)',
          900: 'var(--warning-900)',
        },
        success: {
          50: 'var(--success-50)',
          75: 'var(--success-75)',
          100: 'var(--success-100)',
          200: 'var(--success-200)',
          300: 'var(--success-300)',
          400: 'var(--success-400)',
          500: 'var(--success-500)',
          600: 'var(--success-600)',
          700: 'var(--success-700)',
          800: 'var(--success-800)',
          900: 'var(--success-900)',
        },
        // brand colors
        prim: {
          50: 'var(--prim-50)',
          75: 'var(--prim-75)',
          100: 'var(--prim-100)',
          200: 'var(--prim-200)',
          300: 'var(--prim-300)',
          400: 'var(--prim-400)',
          500: 'var(--prim-500)',
          600: 'var(--prim-600)',
          700: 'var(--prim-700)',
          800: 'var(--prim-800)',
          900: 'var(--prim-900)',
        },
        sec: {
          50: 'var(--sec-50)',
          75: 'var(--sec-75)',
          100: 'var(--sec-100)',
          200: 'var(--sec-200)',
          300: 'var(--sec-300)',
          400: 'var(--sec-400)',
          500: 'var(--sec-500)',
          600: 'var(--sec-600)',
          700: 'var(--sec-700)',
          800: 'var(--sec-800)',
          900: 'var(--sec-900)',
        },
        // feedback colors
        feedback: {
          success: 'var(--feedback-success)',
          warning: 'var(--feedback-warning)',
          error: 'var(--feedback-error)',
          disabled: 'var(--feedback-disabled)',
          flag: 'var(--feedback-flag)',
        },
      },

      width: {
        45: '11.25rem', // w-[180px] equivalente
        55: '13.75rem', // w-[220px] equivalente
        35: '8.75rem', // w-[140px] equivalente
        22: '90px',
        50: '200px',
        81: '330px',
      },
      maxWidth: {
        90: '22.5rem',
      },
      minWidth: {
        22: '90px',
      },
      height: {
        0.75: '3px',
        30: '120px',
      },
      padding: {
        2.5: '0.625rem',
      },
      rotate: {
        270: '270deg',
      },
      textColor: {
        inverted: 'var(--text-inverted)',
        'low-emphasis': 'var(--text-low-emphasis)',
        'middle-emphasis': 'var(--text-middle-emphasis)',
        base: 'var(--text-base)',
        'high-emphasis': 'var(--text-high-emphasis)',
        brand: 'var(--text-brand)',
        footer: {
          DEFAULT: 'var(--footer-text)',
          brand: 'var(--footer-brand)',
        },
        icon: {
          inverted: 'var(--icon-inverted)',
          'lowest-emphasis': 'var(--icon-lowest-emphasis)',
          'low-emphasis': 'var(--icon-low-emphasis)',
          'middle-emphasis': 'var(--icon-middle-emphasis)',
          base: 'var(--icon-base)',
          'high-emphasis': 'var(--icon-high-emphasis)',
          brand: 'var(--icon-brand)',
        },
        cta: {
          primary: 'var(--cta-prim-default)',
          'primary-hover': 'var(--cta-prim-hover)',
          'primary-press': 'var(--cta-prim-press)',
          negative: 'var(--cta-negative)',
          disabled: 'var(--cta-disabled)',
          inverted: 'var(--cta-inverted)',
        },
      },
      textDecorationColor: {
        inverted: 'var(--stroke-inverted)',
        'lowest-emphasis': 'var(--stroke-lowest-emphasis)',
        'low-emphasis': 'var(--stroke-low-emphasis)',
        'middle-emphasis': 'var(--stroke-middle-emphasis)',
        base: 'var(--stroke-base)',
        brand: 'var(--stroke-brand)',
      },
      backgroundColor: {
        primary: 'var(--bg-primary)',
        secondary: 'var(--bg-secondary)',
        brand: 'var(--bg-brand)',
        cta: ctaColors,
        footer: {
          primary: 'var(--footer-bg-primary)',
          secondary: 'var(--footer-bg-secondary)',
        },
      },
      borderColor: {
        inverted: 'var(--stroke-inverted)',
        'lowest-emphasis': 'var(--stroke-lowest-emphasis)',
        'low-emphasis': 'var(--stroke-low-emphasis)',
        'middle-emphasis': 'var(--stroke-middle-emphasis)',
        base: 'var(--stroke-base)',
        brand: 'var(--stroke-brand)',
      },
      fill: {
        current: 'currentColor',
        text: {
          inverted: 'var(--text-inverted)',
          'low-emphasis': 'var(--text-low-emphasis)',
          'middle-emphasis': 'var(--text-middle-emphasis)',
          base: 'var(--text-base)',
          'high-emphasis': 'var(--text-high-emphasis)',
          brand: 'var(--text-brand)',
        },
        icon: {
          inverted: 'var(--icon-inverted)',
          'lowest-emphasis': 'var(--icon-lowest-emphasis)',
          'low-emphasis': 'var(--icon-low-emphasis)',
          'middle-emphasis': 'var(--icon-middle-emphasis)',
          base: 'var(--icon-base)',
          'high-emphasis': 'var(--icon-high-emphasis)',
          brand: 'var(--icon-brand)',
        },
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        'md-primary': 'var(--shadow-md-primary)',
        'md-top': 'var(--shadow-md-top)',
        'md-center': 'var(--shadow-md-center)',
        'md-bottom': 'var(--shadow-md-bottom)',
        lg: '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -4px rgba(0, 0, 0, 0.01)',
        xl: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 8px 10px -6px rgba(0, 0, 0, 0.01)',
        '2xl': '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
        popup: '0px 1px 3px 0px rgba(0, 0, 0, 0.10), 0px 1px 2px -1px rgba(0, 0, 0, 0.10)', // used in or-popup-product-added
        select: '0px 1px 2px -1px rgba(0, 0, 0, 0.10), 0px 1px 3px 0px rgba(0, 0, 0, 0.10)', // used in ml-form-field select
        blur: '0px 8px 16px 0px rgba(21, 21, 21, 0.04);', // used n ml-card-product-recommendation
      },
      spacing: {
        0.5: '0.125rem' /* 2px */,
        1.5: '0.375rem' /* 6px */,
        2.5: '0.625rem' /* 10px */,
        3.5: '0.875rem' /* 14px */,
      },
      letterSpacing: {
        0.125: '0.031em' /* 0.5px */,
        0.1: '0.025em' /* 0.4px */,
        0.05: '0.013em' /* 0.2px */,
      },
      strokeWidth: {
        4: 'var(--stroke-width-4)',
        8: 'var(--stroke-width-8)',
      },
      borderRadius: {
        '4xl': 'var(--border-radius-4xl)' /* 32px */,
      },
    },
  },
  variants: {
    extend: {
      fontWeight: ['hover', 'active', 'disabled'],
      borderWidth: ['hover', 'active', 'disabled'],
      borderColor: ['hover', 'active', 'disabled'],
      backgroundColor: ['active', 'disabled', 'focus', 'hover'],
      textColor: ['hover', 'active', 'disabled'],
      boxShadow: ['hover', 'active', 'disabled'],
    },
  },
  plugins: [container],
}
